# Generated by Django 2.0.6 on 2018-06-15 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180615_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 14, 54, 46, 624004, tzinfo=utc)),
        ),
    ]
