# Generated by Django 2.0.7 on 2018-07-29 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180728_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='currentValue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 19, 48, 33, 169246, tzinfo=utc)),
        ),
    ]
