# Generated by Django 2.0.7 on 2018-08-01 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180729_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='currentValue',
            new_name='currentvalue',
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 9, 9, 35, 835114, tzinfo=utc)),
        ),
    ]
