# Generated by Django 2.0.6 on 2018-06-16 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180615_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor1',
            new_name='Sensor',
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 14, 6, 51, 131222, tzinfo=utc)),
        ),
    ]
