# Generated by Django 2.0.7 on 2018-08-01 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180801_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 9, 13, 6, 339982, tzinfo=utc)),
        ),
    ]
