# Generated by Django 2.0.7 on 2018-08-01 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20180801_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='currentvalue',
        ),
        migrations.AddField(
            model_name='sensorvalue',
            name='type',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 9, 45, 14, 665424, tzinfo=utc)),
        ),
    ]
